[versions]

# AndroidX
androidx-activity-compose = "1.10.0"

# Koin
koin = "4.0.4"

[plugins]
# ...

[libraries]

# AndroidX
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }

# Koin
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
